name: compose
description: Compose functions in dart
version: 0.0.1
homepage: https://github.com/shindakioku/compose
author: firstlast <shindakioku@gmail.com>

environment:
  sdk: '>=2.0.0-dev.67.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0